import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Header from "~/components/header";

const SingleListingPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Place To Stay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto px-6 py-6 sm:px-6 md:max-w-7xl xl:px-0">
        <div>Listing View</div>
      </main>
    </>
  );
};

export default SingleListingPage;
